#!/bin/mksh

NS="$(uuidgen -t)"
I=0

for x in $(find /run/media/grobe0ba/disk/DCIM/100NIKON -type f -print0 | xargs --null);
do
    I=$((I+1));
    echo "${x} -> ${NS} - ${I}.jpg";
    cp "${x}" "${NS} - ${I}.jpg";
done
