#!/usr/local/bin/bash

if [[ -z "$1" ]];
then
	echo "Usage: $0 [snapshot name]" >&2
	exit 1
fi

MOUNTS=$( zfs list | sed -e 's/  */ /g' | cut -d' ' -f5 | grep -v none |grep -v MOUNTPOINT | xargs)

for x in $MOUNTS;
do
	sudo rm $x/.zfs/snapshot/$1
done
