#!/bin/bash
HDA=/home/grobe0ba/qemu/sda
if [[ ! -a $HDA ]]; then
	qemu-img create -f qcow2 $HDA 100G
fi

show_help() {
	cat << EOF
Usage: $0 -dsvixau [-b boot device] [-c cdrom image] [-f floppy image] [-n NIC model] [-m memory] [-h hard drive] [-z qemu system]
	d: Do not run in screen
	s: Set display type
		spice
		sdl
		vnc
	v: Disable VIRTIO
	i: Disable SCSI
	x: Wipe and start over
	a: Monitor on STDIO
	u: USB tablet
EOF
}

SCR=
SCR="screen -dmS qemu"
#QDISP="-display vnc=127.0.0.1:0"
#QDISP="-display sdl -vga std"
QDISP="-vga qxl -spice port=5900,addr=127.0.0.1,disable-ticketing -device virtio-serial-pci -device virtserialport,chardev=spicechannel0,name=com.redhat.spice.0 -chardev spicevmc,id=spicechannel0,name=vdagent"
BOOT=c
MEM=1345

#Old Networking
#-net tap,ifname=qemu,script=no,downscript=no,id=net0
ETH0="-netdev tap,ifname=qemu,script=no,downscript=no,id=net0 -device virtio-net-pci,netdev=net0"
ETH1="-netdev tap,ifname=qemu1,script=no,downscript=no,id=net1 -device virtio-net-pci,netdev=net1"
HDDEV=virtio
MON=
QEMU_SYSTEM="qemu-system-x86_64 -enable-kvm"
set_qdisp()
{
	case "$1" in
		spice)
			QDISP="-vga qxl -spice port=5900,addr=127.0.0.1,disable-ticketing -device virtio-serial-pci -device virtserialport,chardev=spicechannel0,name=com.    redhat.spice.0 -chardev spicevmc,id=spicechannel0,name=vdagent"
			;;
		sdl)
			QDISP="-display sdl -vga std"
			;;
		vnc)
			QDISP="-display vnc=127.0.0.1:0"
			;;
		'?')
			show_help >&2;
			exit 1
			;;
	esac
}

while getopts "ds:n:b:c:f:xm:vh:qiaz:" opt; do
	case "$opt" in
		q)
			show_help >&2
			exit
			;;
		s)
			set_qdisp $OPTARG
			;;
		d)
			SCR=""
			;;
		b)
			BOOT=$OPTARG
			;;
		c)
			CDROM="-drive media=cdrom,index=2,file=$OPTARG"
			;;
		v)
			HDDEV=scsi
			ETH0='-netdev tap,ifname=qemu,script=no,downscript=no,id=net0'
			ETH1='-netdev tap,ifname=qemu1,script=no,downscript=no,id=net1'
			;;
		i)
			HDDEV=ide
			;;
		f)
			FLOPPY="-fda $OPTARG"
			;;
		n)
			NMODEL=",model=$OPTARG"
			;;
		x)
			rm $HOME/qemu/sda
			exit
			;;
		m)
			MEM=$OPTARG
			;;
		h)
			HDA=$OPTARG
			;;
		a)
			MON="-monitor stdio"
			;;
		u)
			USBTABLET="-device usb-tablet"
			;;
		z)
			QEMU_SYSTEM=$OPTARG
			;;
		'?')
			show_help >&2
			exit 1
			;;
	esac
done

nice -n19 $SCR $QEMU_SYSTEM -m $MEM -drive media=disk,if=$HDDEV,index=0,file=$HDA $FLOPPY $CDROM $MON -boot $BOOT $QDISP -net nic$NMODEL $ETH0 -net nic$NMODEL $ETH1 -device piix4-usb-uhci -device virtio-balloon $USBTABLET
sleep 5
spicec -h 127.0.0.1 -p 5900 >/dev/null 2>&1 &
